quintel/etlocal

Gemfile
Gemfile.lock
app/assets/javascripts/dataset_interface/change_trigger.js
app/assets/javascripts/sliders/slider.js
app/assets/javascripts/sliders/slider_group.js
app/assets/javascripts/sliders/slider_group_collection.js
app/models/etsource.rb
app/models/interface_element.rb
config/interface_elements/area/area_advanced.yml
config/interface_elements/buildings/buildings_energy_demand.yml
config/interface_elements/buildings/buildings_energy_supply.yml
config/interface_elements/energy/energy.yml
config/interface_elements/households/households.yml
config/interface_elements/households/households_energy_demand.yml
config/interface_elements/households/households_energy_supply.yml
config/interface_elements/industry/industry.yml
config/interface_elements/industry/industry_chemical.yml
config/interface_elements/industry/industry_metal.yml
config/locales/en_attributes.yml
config/locales/en_dataset_edits.yml
config/locales/en_datasets.yml
config/locales/nl_attributes.yml
config/locales/nl_dataset_edits.yml
config/locales/nl_datasets.yml
spec/models/editable_attributes_collection_spec.rb

Updated the front-end:
- Changed all input fields with unit '%' to proper sliders. This should fix: https://github.com/quintel/etlocal/issues/118
- Added/removed keys and sparse graph queries to fix Semaphore errors (goes with https://github.com/quintel/etsource/pull/1769)
- Simplified front-end by removing ``input_buildings_solar_pv_own_use_share``, ``input_households_solar_pv_own_use_share``.
When testing this locally, some sliders don't show up properly (see screenshots). Can you have a quick look whether this happens on your machine as well @antw? Not sure if related, by in my browser console I get quite some errors like ``tile does not exist`` from mapbox.com.
Sliders not showing up or cannot 'slide' them (tab Industry -> Metal and Industry -> Chemical):
Sliders showing up but cannot …

Front end update

---

db/migrate/20181029145343_remove_empty_datasets.rb
db/schema.rb

Removes the old datasets whose commits and datasets edits were removed when the DB was reseeded. Datasets with one or more commits, or belonging to anyone other than the Robot, are left untouched.

Remove all robot datases with zero commits

---

app/controllers/api/v1/exports_controller.rb
app/models/dataset.rb
spec/controllers/api/v1/exports_controller_spec.rb

ETModel doesn't display datasets in the dataset selector and/or open a dataset if the dataset name contains special characters (like ``(`` or ``.``). 
I modified the dataset exporter to ensure that datasets exported to ETSource do not contain these characters:
- replaces accented characters with non-accented characters
- replaces spaces with underscores
- removes dots, parentheses, inverted commas
Tested with the Groningen datasets and it seems to work fine.
Priority is low.

dataset exporter: replace special characters

---

db/migrate/20181218173807_fix_incorrect_building_lighting_shares.rb
db/schema.rb

I updated *all* datasets which had the incorrect initial values, not just the Quintel datasets. This means that any third-party versions which contained the error are also fixed.
Closes quintel/etlocal#153

Fix incorrect initial building lighting shares

---

app/models/dataset.rb
config/locales/en_datasets.yml
config/locales/nl_datasets.yml

- Distinguish `res` as area group when exporting the dataset to ETSource
- Add translations for the RES regions

Distinguish RES region as area group

---

config/interface_elements/industry/industry_food.yml
config/interface_elements/industry/industry_paper.yml
config/locales/en_attributes.yml
config/locales/en_dataset_edits.yml
config/locales/nl_attributes.yml
config/locales/nl_dataset_edits.yml
db/migrate/20200325172206_add_food_paper_electricity_splits.rb
db/schema.rb

Adds interface elements for the split of electricity demand of food and paper into processes and heat.
Migration to use default NL2015 value for all region

Add food and paper electricity splits to front-end and database

---

db/migrate/20200327080450_minor_update_regions_block_heating.rb
db/migrate/20200327080450_minor_update_regions_block_heating/commits.yml
db/migrate/20200327080450_minor_update_regions_block_heating/data.csv
db/schema.rb

These five regions had a `heat_share_of_apartments_with_block_heating` higher than 1.0. Updated the value to the Dutch average value

Add migration that updates block heating share for five regions

---

app/controllers/api/v1/exports_controller.rb
app/controllers/commits_controller.rb
app/forms/dataset_edit_form.rb
app/models/dataset.rb
app/models/etsource.rb
app/services/calculable_validator.rb
app/services/csv_importer.rb
app/services/csv_importer/schema.rb
app/services/exporter.rb
db/migrate/20200424141616_remove_default_nl_for_dataset_country.rb
db/schema.rb
spec/factories/dataset.rb
spec/fixtures/seeds/data.csv
spec/forms/dataset_edit_form_spec.rb
spec/models/dataset_spec.rb
spec/services/csv_importer/schema_spec.rb
spec/services/csv_importer_spec.rb
spec/services/dataset_importer_spec.rb

Add validation of country: needs to be a full Atlas set
Calculate base_dataset by combining country and analysis_year and checking if this is a full Atlas set. Default to country.
Adjust specs, exporter and edit-forms to work with base_dataset and without country default

Remove country defaults and calc base_dataset for Datasets

---

config/interface_elements/energy/energy_renewable_electricity_production.yml
config/locales/en_attributes.yml
config/locales/nl_attributes.yml
db/migrate/20200605081642_add_hydro_mountain_demand.rb
db/schema.rb

Before hydro mountain production was derived from the parent country of a dataset. For Northern Ireland this resulted in some hydro mountain production, because the UK has hydro power in mountains. Therefore, the demand can now be set in ETLocal and has been set to zero for all ETLocal dataset as there is no hydro power in mountains :)

Adding hydro power mountain production

---

app/assets/javascripts/areas/areas.search.js
app/assets/stylesheets/areas.sass
app/controllers/datasets_controller.rb
app/models/dataset.rb
config/routes.rb
spec/models/dataset_spec.rb

I replaced the current map based search with a dataset based search.
You can put in either a geoID or a dataset name, and a fuzzy search is performed. The fuzzy search ignores lower/uppercase, and looks for the input to be _part_ of a name or geoID. So the input _"rot"_ for example gives the options of Rotterdam, RES regio Rotterdam-Den Haag, but also Grote Plas. This fuzzy search does not corect typos.
You can click one of the search results (or when there is only one result, this happens immeadiatly) and the dataset opens in the well known pop-up.
Closes #255

Replace map search with dataset seacrh

---

Gemfile
Gemfile.lock
app/services/exporter.rb
lib/tasks/etsource.rake
spec/services/exporter_spec.rb

The task `etsource:export` now takes the optional argument `REBUILD` which defaults to true if not set. The dataset is detroyed before being build back up again,  this ensures symlinks and scaled data being up to date.
I also set the default for `TIME_CURVES_TO_ZERO` from false to true. With no parameters other than the datasets, the task now rebuilds and does not scale time curves (but sets them to zero).
Closes #250

Rebuild dataset on default when exporting to etsource

---

app/assets/stylesheets/style.sass
app/models/dataset_edit.rb
app/views/interface_elements/_interface_element.slim
config/locales/en.yml
config/locales/en_headers.yml
config/locales/nl.yml
config/locales/nl_headers.yml
spec/models/dataset_edit_spec.rb

A restyle of the version history as requested in #284.
How it was:
How it is now:
The part that says how the value changed is now enlarged and in a more prominent place. 
If the user that changed the value belongs to a group (like Quintel) this group is shown. So no more changes by Robot.
Closes #284

Restyle the version history

---

config/interface_elements/agriculture/agriculture_energy_demand.yml
config/interface_elements/buildings/buildings_energy_demand.yml
config/interface_elements/households/households_energy_demand.yml
config/interface_elements/industry/industry_heat_chp.yml
config/locales/en_descriptions.yml
config/locales/en_headers.yml
config/locales/en_interface_elements.yml
config/locales/nl_descriptions.yml
config/locales/nl_headers.yml
config/locales/nl_interface_elements.yml
db/migrate/20210803161212_add_oil_mix_sliders.rb
db/schema.rb

Adds sliders to set the oil mix as described in quintel/etmodel#3760 for local datasets. All mixes are set to an initial distribution of:
- 100% _"Other oil"_ (crude oil carrier)
- 0% for all other oil types
Sliders are added to the energy demand tabs of their respecive sectors:
---
See also quintel/etsource#2496
And quintel/etmodel#3776
---
Edit: The build will continue to fail on Semaphore unless the ETSource PR is merged, as it is now comparing this branch of ETLocal to the master branch of ETSource which are not compatible.

Add oil mix sliders

---

db/migrate/20220106152238_add_flh_defaults.rb
db/schema.rb

Adds new commits with default values for the full load hours of power plants for EU datasets. The default is set when a plants FLH were 0.
| key | new default |
| --- | --- |
| energy_power_ultra_supercritical_coal_full_load_hours | 5440 |
| energy_power_supercritical_coal_full_load_hours | 5000 |
| energy_power_ultra_supercritical_lignite_full_load_hours | 7500 |
| energy_power_ultra_supercritical_network_gas_full_load_hours | 4000 |
| energy_power_turbine_network_gas_full_load_hours | 4000 |
| energy_power_combined_cycle_network_gas_full_load_hours | 4000 |
| energy_power_ultra_supercritical_crude_oil_full_load_hours | 4000 |
| energy_power_nuclear_gen2_uranium_oxide_full_load_hours | 7630 |
| energy_power_supercritical_waste_mix_full_load_hours | 4100 |
| …

Add default FLH for EU power plants

---

config/interface_elements/energy/energy_energy_demand.yml

The Eurostat energy balance contains the product 'Biogases'. In the CHP script, all the biogas on the transformation input flows for combined heat and power producers (both main activity and autoproducers) are assigned to the local biogas CHP engine (`energy_chp_local_engine`). All the remaining biogas is then assumed to be upgraded to greengas and mixed into the national gas network
In the corresponding [interface_element](https://github.com/quintel/etlocal/blob/production/config/interface_elements/energy/energy_energy_demand.yml) however, instead of subtracting the biogas flows for combined heat and power from the Total energy supply, the transformation input of only the autoproducers was added to get the total greengas demand. This has led to an overestimation of the greengas …

Update mapping of greengas demand for ENTSO datasets

---

config/interface_elements/energy/energy_efficiency.yml

This is a temporary solution for quintel/etdataset#949
If statements are added to CHPs (gas, or gas-based CHPs), that assign a fallback efficiency when the `energy_balance_generator` [script](https://github.com/quintel/etdataset/tree/master/tools/energy_balance_generator) has produced efficiencies > 100%

Add fallback efficiency for EU datasets with efficiencies > 100%

---

db/migrate/20240701091330_rename_bergen_limburg.rb
db/schema.rb

Adds a migration script to rename GM0893 to "Bergen" instead of "Bergen (L.)".

Rename GM0893 Bergen_L to Bergen

---

config/locales/en.yml
config/locales/nl.yml

This PR fixes:
- Locales of Norway: quotation marks needed in translations
- Locales of other areas: which have eu as parent dataset
Issues (that are now fixed):

Fixes locales of Norway and other areas

---

config/locales/en.yml
config/locales/nl.yml
data/datasets/energy_balance/README.md

This PR:
- Adds a README.md file to the energy_balance folder
- Updates the key descriptions related to energy balance keys where links to the Eurostat EB are removed and old file links are updated with working links
Fixes:
- https://github.com/quintel/etlocal/issues/559
- the first proposed solution of https://github.com/quintel/etlocal/issues/557

Energy balance README and update key descriptions

---

db/migrate/20250203094009_retire_gm0345ha_het_ambacht_veenendaal.rb
db/schema.rb

Retirement of dataset GM0345HA_Het_Ambacht_Veenendaal, which was a custom dataset generated for a specific project. 
Goes with https://github.com/quintel/etsource/pull/3203

Retire dataset GM0345HA_Het_Ambacht_Veenendaal

---

app/services/amalgamator/processor/base.rb
app/services/amalgamator/processor/combine.rb
app/services/amalgamator/processor/separate.rb
config/interface_elements/area/area_infrastructure.yml
config/interface_elements/households/households_housing_stock.yml
spec/services/amalgamator/processor/base_spec.rb
spec/services/amalgamator/processor/combine_spec.rb

While updating the RES-regions to 2019 we encountered the following issues :
The Eemsdelta dataset had incorrect share values for useful demand per housing and period.
> 1. The Eemsdelta dataset had incorrect share values for useful demand per housing and period. 
> 2. The combination method weighted_average doesn't work as desired when calculating with shares (example: all keys of parent group share_useful_demand_houses, since the resulting shares add up to >1.0.
> 3. Excel rounding issue where summed value of group shares are for instance 1.0000000001 (this is for instance the case for parent group transport_road_electricity_distribution).
The first issue was fixed by updating the household shares in the Eemsdelta municipality and migrating this change on etlocal. --> This will be fixed …

Update amalgamator for municipal datasets

---

config/interface_elements/industry/industry_steel.yml

This PR closes #538 by altering the EB method for the key input_energy_blastfurnace_transformation_coal_input_demand. 
In this alteration the flow of the carrier "coke oven coke" is now subtracted from the carrier group "Coal incl lignite and peat".
I prefered this approach to adding a new carrier group for coal, since we already have 2 carrier groups for Coal. 
Goes together with:
https://github.com/quintel/etsource/pull/3300
Assigned to @mabijkerk for now, reassign at will.

Alter EB method for coke oven cokes in steel sector
