app/assets/stylesheets/areas.sass
app/assets/stylesheets/style.sass

Originally part of https://github.com/quintel/etlocal/pull/63
---
@michieldenhaan I assigned you this PR. I'll setup ETLocal for you locally so you can check these pull requests. Come and see me when you have time.

Fix the height of the map

---

app/assets/javascripts/areas/areas.dataset_selector.js
config/layers.yml
vendor/assets/stylesheets/quinn.scss

Originally part of https://github.com/quintel/etlocal/pull/63
---
@michieldenhaan I assigned you this PR. I'll setup ETLocal for you locally so you can check these pull requests. Come and see me when you have time.

Various small issues

---

Gemfile
Gemfile.lock
config/interface_elements/agriculture/agriculture.yml
config/locales/en_attributes.yml
config/locales/en_dataset_edits.yml
config/locales/nl_attributes.yml
config/locales/nl_dataset_edits.yml
db/migrate/20191002131648_agriculture_keys.rb
db/schema.rb

To make it easier to map local data to ETLocal, the agriculture interface elements have been revamped to have greater control over final demand for electricity and steam hot water.

front-end changes for 2017 update

---

config/interface_elements/agriculture/agriculture.yml
config/interface_elements/buildings/buildings_energy_supply.yml
config/interface_elements/energy/energy_fossil_electricity_production.yml
config/interface_elements/energy/energy_heat_production.yml
config/interface_elements/energy/energy_renewable_electricity_production.yml
config/interface_elements/households/households_energy_supply.yml
config/interface_elements/industry/industry.yml
config/locales/en_attributes.yml
config/locales/en_dataset_edits.yml
config/locales/en_descriptions.yml
config/locales/nl_attributes.yml
config/locales/nl_dataset_edits.yml
config/locales/nl_descriptions.yml
db/migrate/20191203090847_upate_local_chps.rb
db/migrate/20191203102125_set_new_heaters_to_zero.rb
db/migrate/20191203103441_set_new_heat_losses_to_zero.rb
db/migrate/20191203105604_rename_heaters.rb
db/migrate/20191203122218_merge_heaters.rb
db/schema.rb

Merge after:
https://github.com/quintel/etlocal/pull/212

Heat network changes

---

Gemfile
Gemfile.lock
app/models/dataset.rb
app/models/interface_element.rb
config/interface_elements/energy/energy_full_load_hours.yml
config/locales/en_attributes.yml
config/locales/en_dataset_edits.yml
config/locales/en_datasets.yml
config/locales/en_descriptions.yml
config/locales/nl_attributes.yml
config/locales/nl_dataset_edits.yml
config/locales/nl_datasets.yml
config/locales/nl_descriptions.yml
config/menu.yml
db/migrate/20200526155129_add_full_load_hours.rb
db/migrate/20200527131501_remove_temp_antwerp_commit.rb
db/schema.rb

Adding flhs for most used power plants to ETLocal

---

config/interface_elements/energy/energy_biomass.yml
config/interface_elements/energy/energy_energy_demand.yml
config/locales/en_attributes.yml
config/locales/en_dataset_edits.yml
config/locales/nl_attributes.yml
config/locales/nl_dataset_edits.yml
db/migrate/20210310135436_set_regasified_lng_in_gas_network_to_zero.rb
db/schema.rb

Add new interface element for regasified LNG demand in gas network

---

app/assets/javascripts/sliders/slider.js
app/views/interface_elements/_interface_element.slim

Fix issues #282 and #283

---

config/interface_elements/buildings/buildings_energy_demand.yml
config/interface_elements/industry/industry_heat_chp.yml

Updating EU datasets: fix two errors

---

db/migrate/20220907075046_update_malta_flh.rb
db/migrate/20220907075046_update_malta_flh/commits.yml
db/migrate/20220907075046_update_malta_flh/data.csv
db/schema.rb

See quintel/etsource#2748.
Corresponds with:
- https://github.com/quintel/etdataset/pull/940
- https://github.com/quintel/etsource/pull/2749

Scale down MT solar PV flh to account for non-concurrency

---

config/interface_elements/transport/transport_plane_transport.yml
config/interface_elements/transport/transport_ship_transport.yml
config/locales/en_interface_elements.yml
config/locales/nl_interface_elements.yml
db/migrate/20220916150940_set_electric_planes_ships_to_zero.rb
db/schema.rb

This PR goes with:
- ETModel: https://github.com/quintel/etmodel/pull/4012
- ETSource: https://github.com/quintel/etsource/pull/2756
- ETDataset: https://github.com/quintel/etdataset/pull/944
- ETLocal: https://github.com/quintel/etlocal/pull/421
- documentation: https://github.com/quintel/documentation/pull/122
It contains a number of additions and improvements:
- Addition of electric inland ships for domestic navigation
- Addition of electric and hydrogen planes for domestic aviation
- Addition of hybrid flexible power-to-heat to agriculture sector
- Addition of water water heat pump without thermal storage to agriculture sector
- Possibility to delay emissions from captured CO2 for 'Other utilisation' indefinitely
- Updated inputs of Direct Air Capture
- Updated total potential of …

Several improvements

---

config/interface_elements/industry/industry_other.yml

Closes https://github.com/quintel/etlocal/issues/424
Goes with https://github.com/quintel/etsource/pull/2772

Fix calculation of other industry demand in EU datasets

---

config/locales/en_interface_elements.yml
config/locales/nl_interface_elements.yml
db/migrate/20221104083301_rename_fertilizer_residual_heat_edge.rb
db/schema.rb

We forgot two things after renaming an ETLocal key:
- also renaming the key in the locales
- change the key in all datasets with a dataset migration!

Rename fertilizer edge in locales and all datasets

---

config/interface_elements/energy/energy_efficiency.yml
config/interface_elements/energy/energy_full_load_hours.yml
config/interface_elements/industry/industry_heat_chp.yml
config/interface_elements/transport/transport_ship_transport.yml
config/locales/en_interface_elements.yml
config/locales/nl_interface_elements.yml
db/migrate/20221118110919_add_domestic_navigation_bio_ethanol.rb
db/migrate/20221130084843_add_hydrogen_plants_industry.rb
db/schema.rb

This PR adds:
- Bio-ethanol for domestic navigation
- Hydrogen heater and CHP turbine for the industrial heating network
This goes with:
- https://github.com/quintel/etdataset/pull/958
- https://github.com/quintel/etsource/pull/2817
- https://github.com/quintel/etmodel/pull/4047

Add various model improvements

---

db/migrate/20230214141717_northern_ireland_interconnector_capacity.rb
db/migrate/20230214141717_northern_ireland_interconnector_capacity/commits.yml
db/migrate/20230214141717_northern_ireland_interconnector_capacity/data.csv
db/schema.rb

As requested by DfE, value of interconnector is set to 500 MW (Moyle Interconnector).

Update interconnector capacity for Northern Ireland

---

db/migrate/20231211143456_revise_flh_noord_holland.rb
db/migrate/20231211143456_revise_flh_noord_holland/commits.yml
db/migrate/20231211143456_revise_flh_noord_holland/data.csv
db/schema.rb

Set values to the Dutch average (based on the NL2019 dataset)
Goes with https://github.com/quintel/etsource/pull/2975

Revise full load hours for wind turbines in Noord-Holland

---

db/migrate/20240507094837_smallingerland_2019_potentials_wind_solar.rb
db/migrate/20240507094837_smallingerland_2019_potentials_wind_solar/commits.yml
db/migrate/20240507094837_smallingerland_2019_potentials_wind_solar/data.csv

Goes together with:
[Smallingerland areable land update #3078 on Etsource](https://github.com/quintel/etsource/pull/3078)
This PR updates the potential areable land for renewables in the municipality of Smallingerland.

Smallingerland areable land update

---

app/lib/dataset_source/entso/file.rb

Small change to handle encrypted energy balance file names.

Handle encrypted Energy Balances

---

db/migrate/20241210101108_noord_holland_agriculture_electricity_fix.rb
db/migrate/20241210101108_noord_holland_agriculture_electricity_fix/commits.yml
db/migrate/20241210101108_noord_holland_agriculture_electricity_fix/data.csv
db/schema.rb

This PR updates the final demand of demand in agriculture for the Province of Noord-Holland. 
Goes together with:
https://github.com/quintel/etsource/pull/3161

Revising electricity final demand in agriculture for the Province of Noord-Holland

---

db/migrate/20250207083918_antwerpen_update.rb
db/migrate/20250207083918_antwerpen_update/commits.yml
db/migrate/20250207083918_antwerpen_update/data.csv
db/schema.rb

Correction on the dataset #567  with full load hours and efficiencies

Update dataset Antwerpen correction

---

config/locales/en_descriptions.yml
config/locales/nl_descriptions.yml

This PR updates the links that refer to the weather conditions page in the ETM. 
Goes with:
- https://github.com/quintel/etmodel/pull/4432
- https://github.com/quintel/etlocal/pull/580
- https://github.com/quintel/documentation/pull/222
Closes https://github.com/quintel/etmodel/issues/4357

Update links to weather conditions page

---

db/migrate/20250317140451_antwerpen_buildings_update.rb
db/migrate/20250317140451_antwerpen_buildings_update/commits.yml
db/migrate/20250317140451_antwerpen_buildings_update/data.csv
db/schema.rb

This PR changes the amount of buildings in the Antwerpen dataset to 45244.0. 
Goes together with:
https://github.com/quintel/etsource/pull/3231

Adding amount of buildings for Antwerpen dataset as discussed with cient
